import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import NavBar from "@/components/nav";
import RegisterGsapPlugins from "@/components/RegisterGsapPlugins";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const blogsBaseUrl =
  process.env.NEXT_PUBLIC_BLOGS_BASE_URL ?? "https://stonefarms.org";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link
          rel="stylesheet"
          id="premium-addons-css"
          href={`${blogsBaseUrl}/wp-content/plugins/premium-addons-for-elementor/assets/frontend/min-css/premium-addons.min.css?ver=4.10.79`}
          media="all"
        />

        <link
          rel="stylesheet"
          id="chaty-front-css-css"
          href={`${blogsBaseUrl}/wp-content/plugins/chaty/css/chaty-front.min.css?ver=3.3.51739355781`}
          media="all"
        />

        <link
          rel="stylesheet"
          id="dashicons-css"
          href={`${blogsBaseUrl}/wp-includes/css/dashicons.min.css?ver=6.7.5`}
          media="all"
        />

        <link
          rel="stylesheet"
          id="elementor-frontend-css"
          href={`${blogsBaseUrl}/wp-content/plugins/elementor/assets/css/frontend.min.css?ver=3.27.1`}
          media="all"
        />

        <link
          rel="stylesheet"
          id="swiper-css"
          href={`${blogsBaseUrl}/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css?ver=8.4.5`}
          media="all"
        />
        <link
          rel="stylesheet"
          id="e-swiper-css"
          href={`${blogsBaseUrl}/wp-content/plugins/elementor/assets/css/conditionals/e-swiper.min.css?ver=3.27.1`}
          media="all"
        />
        <link
          rel="stylesheet"
          id="widget-image-carousel-css"
          href={`${blogsBaseUrl}/wp-content/plugins/elementor/assets/css/widget-image-carousel.min.css?ver=3.27.1`}
          media="all"
        />

        <link
          rel="stylesheet"
          id="google-fonts-1-css"
          href="https://fonts.googleapis.com/css?family=Roboto%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CRoboto+Slab%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&amp;display=swap&amp;ver=6.7.5"
          media="all"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com/" />
        <link
          rel="stylesheet"
          id="elementor-post-998-css"
          href={`${blogsBaseUrl}/wp-content/uploads/elementor/css/post-998.css?ver=1777772819`}
          media="all"
        ></link>
        <script
          src={`${blogsBaseUrl}/wp-includes/js/jquery/jquery.min.js?ver=3.7.1`}
          id="jquery-core-js"
        ></script>
        <script
          src={`${blogsBaseUrl}/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1`}
          id="jquery-migrate-js"
        ></script>
        <script
          src={`${blogsBaseUrl}/wp-content/plugins/elementor/assets/lib/swiper/v8/swiper.min.js?ver=8.4.5`}
          id="swiper-js"
        ></script>
      </head>
      <RegisterGsapPlugins />
      <body className="bg-green-50 relative overflow-x-hidden">
        <div className="fixed w-full z-50">
          <div className="px-[5%] pt-10 pb-2 bg-primary/10 shadow-2xl backdrop-blur-xl rounded-b-2xl">
            <NavBar />
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
