import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav";
import RegisterGsapPlugins from "@/components/RegisterGsapPlugins";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <RegisterGsapPlugins />
      <body className="bg-green-50 relative overflow-x-hidden">
        <div className="fixed w-full z-50">
          <div className="px-[5%] pt-10 pb-2 bg-primary/10 shadow-2xl backdrop-blur-xl rounded-b-2xl">
            <NavBar />
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
